### ISSUE TITLE
OpenID Connect Client authentication 

### ISSUE THREAD

**Issue by Ed-Mar** [ctron/yew-oauth2#10]
Quick question, I am looking for client authentication for OpenID, but did not find a field in the configuration additional field for OpenID. Is there something I am missing, or are non public clients not implemented nor planned. 

Otherwise, **great work.**

**Comment by ctron** [comment]
I am not sure I fully understand the question. OpenID Connect support can be enabled using a feature flag (as it adds additional dependencies). See the example here: ttps://github.com/ctron/yew-oauth2/blob/091ad23cd93cd5502db5e0a90a8e28924e8f0743/yew-oauth2-example/Cargo.toml#L21-L23

And the README here: https://github.com/ctron/yew-oauth2#openid-connect
