### ISSUE TITLE
redirect_uri_mismatch

### ISSUE THREAD

**Issue by collinsmarra** [ctron/yew-oauth2#13]
Hi, this is just a question.
I have been trying to use google-auth. But I keep getting this error even though I have configured my oauth2 client's ID redirect_url correctly. I just used the example available in the docs and haven't modified much.

![image](https://user-images.githubusercontent.com/48761741/220536842-d5a56066-7393-4db3-b9b5-ea6a13d22608.png)

Is there anything I am missing?

```rs
use yew::prelude::*;
use yew_oauth2::prelude::*;
use yew_oauth2::oauth2::*;
// use gloo::console::log;


#[function_component(MyApplication)]
pub fn my_app() -> Html {
    // google login implementation
    let config = Config {
        client_id: "289520722885-3ur4cdpsj0a2phdjh05adrg3jeuvc8ke.apps.googleusercontent.com".into(),
        auth_url: "https://accounts.google.com/o/oauth2/auth".into(),
        token_url: "https://oauth2.googleapis.com/token".into(),
    };
    let scopes = vec![ "https://www.googleapis.com/auth/userinfo.profile".into(),];

    html!(
        <OAuth2 config={config} scopes={scopes}>
            <MyApplicationMain/>
        </OAuth2>
        )
}

#[function_component(MyApplicationMain)]
pub fn my_app_main() -> Html {
    let agent = use_auth_agent().expect("Must be nested inside an OAuth2 component");

    let login = {
        let agent = agent.clone();
        Callback::from(move |_| {
            let _ = agent.start_login();
        })
    };
    let logout = Callback::from(move |_| {
        let _ = agent.logout();
    });

    html!(
        <>
            <Failure><FailureMessage/></Failure>
            <Authenticated>
                <button onclick={logout}>{ "Logout" }</button>
            </Authenticated>
            <NotAuthenticated>
                <button onclick={login}>{ "Login" }</button>
            </NotAuthenticated>
        </>
        )
}

**Comment by ctron** [comment]
When navigating the browser to the OAuth2 server (Google in this case) it adds a parameter to the request which tells the OAuth2 server where to redirect to, after a successful authentication. In most cases this URL must be explicitly allowed through some configuration.

I am not sure how this works exactly with Google, but in Keycloak and GitHub you have some fields to put in the URL. The URL is discovered by yew-oauth2 from the browser:

https://github.com/ctron/yew-oauth2/blob/5c0b4128f47909682fc88c2e6dc7e6a896c65a47/src/agent/mod.rs#L378-L384

You should be able to see the URL in the request send to the Google OAuth2 endpoint (it's URL encoded), and this URL should be allowed on the Google side. For Keycloak it is possible to use wildcards (`*`) to work allow patterns or URLs. That sometimes helps with `localhost` URLs and random ports. It depends on your OAuth2 implementation how and if this is enforced, and what can be configured.

**Comment by collinsmarra** [comment]
Thank you. I added both `http://127.0.0.1:8080` and `http://localhost:8080` as the redirect uri and it seemed to have fixed the error. However, this is the result.


 ![image](https://user-images.githubusercontent.com/48761741/220629653-441d66d8-057c-425b-8a3c-374d9eba4007.png)

This is the response from google servers

![image](https://user-images.githubusercontent.com/48761741/220630827-c4d08809-cf37-4203-98fe-7221281bb495.png)

But I know I am not supposed to pass in the client secret at this point, because the token is to be taken to the backend to be used there. Could I be missing anything here?

**Comment by ctron** [comment]
Cool. You need to set up a client with doesn't require a secret. As this is a web/frontend application, you can't use a secret. In Keycloak terminologies this is a "public client". Not sure how that is called in Google-land.

But if you figure it out, it would be great to let me (any possibly others) know :grinning:

**Comment by collinsmarra** [comment]
I do get the redirect, which is fine. But I think in this case `yew-oauth2`  tries to exchange something with the google servers without the `client_secret`.  So I get the error. 
But for my needs, I wanted to dump the JWT code from google so I can parse them to the backend. That is where I could use the `client_secret`, decode the code, get the needed info and then issue a user new fresh tokens from my own backend.

**Comment by ctron** [comment]
When using yew-oauth2, we are talking about a "public client": https://oauth.net/2/client-types/ … that does not involve a "client secret" as it cannot be kept confidential/secret.

This has been discussed before: https://github.com/ctron/yew-oauth2/pull/3#issuecomment-1195045024 and following … maybe take a look. I think it also mentions/links to Google documentation regarding this.

When communicating with Google APIs, I would expect to only forward the access token (which your backend received from the frontend).

**Comment by ctron** [comment]
Here is the link to Google's documentation: https://developers.google.com/identity/protocols/oauth2/javascript-implicit-flow#oauth-2.0-endpoints

**Comment by ctron** [comment]
Can we close this one?
