### ISSUE TITLE
post_login_redirect doesn't actually redirect if the callback is not used

### ISSUE THREAD

**Issue by ronnybremer** [ctron/yew-oauth2#32]
I was implementing the OpenID workflow in a new Yew app with this crate. Works like a charm until I need to be redirected after login. It removes the URL parameters as returned from `authorize` but doesn't redirect.

Looking at the following piece of code, when no callback is set the function just returns, without deleting the previous URL form local storage nor trying to redirect.

https://github.com/ctron/yew-oauth2/blob/17647840a9a951cee93db56a0cf0f0bb19696a79/src/agent/mod.rs#L448-L456

The documentation earlier in the same file
https://github.com/ctron/yew-oauth2/blob/17647840a9a951cee93db56a0cf0f0bb19696a79/src/agent/mod.rs#L54-L56
states, that the redirect will be "done". I assume that is not the case and I need to implement the callback myself.

Is that correct?

**Comment by ctron** [comment]
Right, the documentation also says:

https://github.com/ctron/yew-oauth2/blob/17647840a9a951cee93db56a0cf0f0bb19696a79/src/agent/mod.rs#L46-L66

Specifically:

https://github.com/ctron/yew-oauth2/blob/17647840a9a951cee93db56a0cf0f0bb19696a79/src/agent/mod.rs#L66

As that's described just a few lines later, I am not sure how to improve this.

**Comment by ronnybremer** [comment]
I added a pull request which hopefully makes that part of the doc clearer.

**Comment by ctron** [comment]
It's merged.
