### ISSUE TITLE
Refresh of access token issue

### ISSUE THREAD

**Issue by ronnybremer** [ctron/yew-oauth2#36]
I have encountered a weird issue I can't quite get my bearings on. Taking to an OpenID IDP which returns an ID token, access token and expires_in setting of 1h (3600 seconds), the console log shows correctly:

```
yew-oauth2-0.10.2/src/agent/mod.rs:300 Starting timeout for: 3569940ms
```

The original request was made at 5:12:43 pm UTC time. I left the browser sit like that and was expecting the refresh to occur shortly before the 1h mark.
However, at 6:59:59 am the next day the refresh happened, and of course failed, as the refresh token was long expired.

```
yew-oauth2-0.10.2/src/agent/mod.rs:508 Triggering refresh
Failed to load resource: the server responded with a status of 400 (Bad Request)
yew-oauth2-0.10.2/src/agent/mod.rs:281 update state: Failed("login result: failed to exchange refresh token: Failed to parse server response")
```

More interesting, yew seemed to have crashed because of the error:

```
panicked at .cargo/registry/src/index.crates.io-6f17d22bba15001f/yew-0.21.0/src/functional/mod.rs:235:49:
assertion `left == right` failed: Hooks are called conditionally.
  left: 6
 right: 1

Stack:

@http://test:8080/frontend-43380d544d4c8f5e.js:642:30
<?>.wasm-function[console_error_panic_hook::Error::new::h0d77e00d11b5a90d]@[wasm code]
<?>.wasm-function[console_error_panic_hook::hook_impl::h95e550010f8cc388]@[wasm code]
<?>.wasm-function[console_error_panic_hook::hook::h5cb0f9de521c2ee5]@[wasm code]
<?>.wasm-function[core::ops::function::Fn::call::h19e24f327623c604]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h1e6ac5d404b8e31b]@[wasm code]
<?>.wasm-function[std::panicking::begin_panic_handler::{{closure}}::h24b0f4622f2766a5]@[wasm code]
<?>.wasm-function[std::sys_common::backtrace::__rust_end_short_backtrace::h19f35d272c126e7c]@[wasm code]
<?>.wasm-function[rust_begin_unwind]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h87755523850ece9e]@[wasm code]
<?>.wasm-function[core::panicking::assert_failed_inner::h161125ff96c9e54a]@[wasm code]
<?>.wasm-function[core::panicking::assert_failed::h4cdcdc97ec396f94]@[wasm code]
<?>.wasm-function[yew::functional::HookContext::assert_hook_context::h004ce7156897b47d]@[wasm code]
<?>.wasm-function[yew::functional::FunctionComponent<T>::render::ha75eb7effad19b6a]@[wasm code]
<?>.wasm-function[<frontend::pages::events::EventList as yew::html::component::BaseComponent>::view::ha60fae9c2ca27d2d]@[wasm code]
<?>.wasm-function[<yew::html::component::lifecycle::CompStateInner<COMP> as yew::html::component::lifecycle::Stateful>::view::h02c2ae1a9aeac644]@[wasm code]
<?>.wasm-function[yew::html::component::lifecycle::ComponentState::render::h8c12f7ba3c02ebe3]@[wasm code]
<?>.wasm-function[<yew::html::component::lifecycle::RenderRunner as yew::scheduler::Runnable>::run::h1b11947cb99d6bfa]@[wasm code]
<?>.wasm-function[yew::scheduler::start_now::scheduler_loop::h9a06f85de98fb156]@[wasm code]
<?>.wasm-function[yew::scheduler::start_now::{{closure}}::h3ad67fcc2dd55041]@[wasm code]
<?>.wasm-function[std::thread::local::LocalKey<T>::try_with::h465cb38313a5333e]@[wasm code]
<?>.wasm-function[std::thread::local::LocalKey<T>::with::h3c1687923204ba3b]@[wasm code]
<?>.wasm-function[yew::scheduler::start_now::h6c0ea53ccddacb93]@[wasm code]
<?>.wasm-function[yew::scheduler::arch::start::{{closure}}::h7f86f6ea030bef9e]@[wasm code]
<?>.wasm-function[wasm_bindgen_futures::task::singlethread::Task::run::h1c7ef169a360c4c1]@[wasm code]
<?>.wasm-function[wasm_bindgen_futures::queue::QueueState::run_all::h0185135a14ce071b]@[wasm code]
<?>.wasm-function[wasm_bindgen_futures::queue::Queue::new::{{closure}}::h7856e231edb3f147]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h0096ac979af67ca1]@[wasm code]

RuntimeError: Unreachable code should not be executed (evaluating 'wasm._dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h0096ac979af67ca1(arg0, arg1, addHeapObject(arg2))')
```

This is a Safari browser session, I will do more testing in Chrome and Firefox to see, if there is any difference.

What might cause the interval to be fired so late?

**Comment by ctron** [comment]
> What might cause the interval to be fired so late?

That's an interesting question. It might very well be that the browser will idle the tab. I could imagine Apple/Safari doing something like this to safe more battery.

The issue (panic) you are running in however seems like a different issue. yew hooks should not be called conditionally, meaning that each hook has to he called the same way in each component. So something like the following is not allowed:

```rust
if foo {
  use_context().do_something();
}
```

And it seems to be coming from `frontend::pages::events::EventList`, which I assume is your frontend code.

Ideally, when this situation happens, the user should be logged out.

**Comment by ronnybremer** [comment]
Thank you @ctron for your insight. I agree, it very like could be a power saving issue. In a busy work environment tabs are very likely to be in the background for a while. Maybe we should have the option to configure a certain "percentage" of the expiration time to set the interval to, for instance
0.5 * expires_in
would refresh the token after half of its time. This might increase the chance of hitting any event before expiry.

Regarding the panic I will check my code. The browser tab was not used at the time, so I assume the error sent a message to the Yew component, which I am not handling correctly.

I'll let you know.

**Comment by ctron** [comment]
IIRC Keycloak has an access token timeout of 5 mins, that would be pretty short. Maybe having a factor and/or max timeout would make sense?

I'll take a look at the failing token refresh. If that happens, the user should get logged out IMO.

**Comment by ctron** [comment]
I just tried to reproduce this with the examples. Here is what I did:

* Re-configure keycloak to a token timeout of 45 seconds
* Fire up the example and log in
* The token has a timeout of 45s and gets refreshed when that reaches 30s
* I kill the session of that user in keycloak
* The next refresh fails, logging out the user with an appropriate error

That all looks good.

**Comment by ctron** [comment]
wrt to the initial problem, I think you might see this: https://discussions.apple.com/thread/7833870?sortBy=best

**Comment by ctron** [comment]
> > wrt to the initial problem, I think you might see this: https://discussions.apple.com/thread/7833870?sortBy=best
> 
> Yes, that makes total sense. Nothing we can do from the developers standpoint I reckon.

Yea, as long the result is something like: user is logged out

**Comment by ronnybremer** [comment]
Ok, I identified the issue for the panic and you were spot on.

In order to redirect the user to a public page of the SPA I determine the logged in state in each component and if not authenticated, do a navigator::push to redirect. However, this eliminates the later calls to use_effect_with etc. to run the hooks. I need to rewrite my code to do the redirection inside the hook, not before.

It always amazes me how we can identify completely unrelated bugs while chasing the main issue. Thank you again @ctron, I will close this issue.

**Comment by ctron** [comment]
> It always amazes me how we can identify completely unrelated bugs while chasing the main issue. Thank you again @ctron, I will close this issue.

Everything is connected ;)
