### ISSUE TITLE
Add support for the Next (after 0.19) version of Yew

### ISSUE THREAD

**Issue by NickLarsenNZ** [ctron/yew-oauth2#5]
I really like this lib, makes things so much easier!

I'm not able to use this component with the latest version of Yew. I know it isn't released yet, but I was hoping to upgrade my app to that in preparation for its release.

The error I'm getting is:

```
34 | pub struct OAuth2<C: Client> {
   | ---------------------------- doesn't satisfy `_: yew::BaseComponent`
   |
   = note: the following trait bounds were not satisfied:
           `yew_oauth2::components::context::OAuth2<OAuth2Client>: yew::BaseComponent`
```

I understand if the Yew code base is too fluid at the moment, so happy if it sits here until it's closer to release. I might come back and try and do it myself.

**Comment by stephenandary** [comment]
Yew 0.20.0 is released now. 

```
the trait bound `yew_oauth2::components::context::OAuth2<OAuth2Client>: yew::Component` is not satisfied
the trait `yew::Component` is implemented for `ContextProvider<T>`
required for `yew_oauth2::components::context::OAuth2<OAuth2Client>` to implement `yew::BaseComponent`
```
Let me know if there is any way I can help, this crate is wonderful. Hoping to try it with oxide-auth on server

**Comment by ctron** [comment]
I will take a look. But I don't promise anything for the next view days :wink:

**Comment by ctron** [comment]
I did a quick check, this will be a bit more trouble than expected:

* This requires an update of `yew-nested-router`, as the "new" router still lacks nested support.
* This also requires an update to `yew-agent 0.2`, which seems to have lost some basic functionality required by `yew-oauth` and `yew-nested-router`.

**Comment by stephenandary** [comment]
Oh no. I am not sure if this Yew update was expected, to me, it seemed like an announcement day of release. I am seeing this issue with many other Yew-dependent crates also e.g. yew-interop.  Do you think it would be beneficial to create an Issue in Yew repo to request that there is more communication before a  release for downstream dependencies to make changes? I will likely just go back to 0.19 for now.

**Comment by ctron** [comment]
I guess the "right" approach is to move to the new context stuff altogether. Or use "real" web workers (which might make sense for yew-oauth, to refresh tokens in "the background").

As with the router, there is long standing issue with this (https://github.com/yewstack/yew/issues/1853). They just shouldn't have deprecated it.

**Comment by ctron** [comment]
So it's Friday, and I started another project: https://github.com/ctron/yew-nested-router (the clue is in the name :grinning:).

This also helps me better understand what changed I need to make for yew-oauth2. But this would also provider a router which can be nested. Though it won't be a drop-in replacement. And, I might take a bit longer than just bumping up the version of Yew.

**Comment by stephenandary** [comment]
Excited to try once I get to using nested routers. I am working on backend today so hopefully next week I can try it out!

**Comment by ctron** [comment]
> Excited to try once I get to using nested routers. I am working on backend today so hopefully next week I can try it out!

Thanks for that. Feedback is always welcome, as are PRs :wink:

**Comment by stephenandary** [comment]
I will do my best! I am newer to Rust and Yew, but once I get flowing I will definitely contribute!

**Comment by ctron** [comment]
@stephenandary there is a PR now for the Yew 0.20 upgrade. I will also do an migration of another project. So far, it looks good.
