### ISSUE TITLE
Notes on using examples

### ISSUE THREAD

**Issue by slyedoc** [ctron/yew-oauth2#7]
Feel free to close this, I could be wrong on these but when trying the examples I had a few issues, though I would document them for others incase its wasn't just me.

### Issue 1

When using the keycloak docker image, the default realm master endpoint
was "account" instead of "frontend".  

> Fix: Change client_id in oauth::config to "account" in app.rs files.

### Issue 2 

Default redirect_url doesn't include localhost

http://localhost:8081/admin/master/console/#/master/clients/

Default username is admin, password is admin123456

Select the "account" client

Update "Valid redirect URIs" with your url, in my case I added:
http://localhost:8080/*
http://127.0.0.1:8080/*

> Note: Yes the readme notes the localhost is enabled by default, but that wasn't true for me, its my first time using keycloak so I could be missing something. 

### Issue 3

Error was "login result: failed to exchange code: Request failed"

Chrome was error due to CORS.

Update "Web Origins", (also found on "account" realm settings) to "+".

**Comment by ctron** [comment]
You might be right with all of these :) …

Regarding issue 2, I was able to fix this by adding `+` there too (like with issue 3). CORS worked for me with Firefox, but adding it should be just fine.

I am wondering why it needs to be `account` though, because it should use whatever the client asks for. So using `frontend` should be fine.

**Comment by ctron** [comment]
@slyedoc I finally found some time to add a Keycloak init script for the compose setup. Now it will create an "example" client and configure it with the correct settings.

It would be great if you could test it, to see if this also fixes the issue for you. Thanks!

**Comment by ctron** [comment]
I will close this. Feel free to comment or re-open if you still have issues.
